/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package claserdf;

import static claserdf.trabajoProp3.existenAfirmaciones;
import static claserdf.trabajoProp3.mostrarDerivaciones;
import java.io.PrintWriter;
import java.util.Iterator;
import org.apache.jena.rdf.model.InfModel;
import org.apache.jena.rdf.model.Model;
import org.apache.jena.rdf.model.ModelFactory;
import org.apache.jena.rdf.model.Property;
import org.apache.jena.rdf.model.RDFNode;
import org.apache.jena.rdf.model.Resource;
import org.apache.jena.rdf.model.Selector;
import org.apache.jena.rdf.model.SimpleSelector;
import org.apache.jena.rdf.model.Statement;
import org.apache.jena.rdf.model.StmtIterator;
import org.apache.jena.reasoner.Derivation;
import org.apache.jena.vocabulary.RDF;
import org.apache.jena.vocabulary.RDFS;

/**
 *
 * @author PAOLO
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ConsultaSubclass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CajaConsulta = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CajaResultados = new javax.swing.JTextArea();
        ConsultaSubpropiedad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Lenguaje_Propiedad = new javax.swing.JTextField();
        Propiedad = new javax.swing.JTextField();
        Clase = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LenguajeDominio = new javax.swing.JTextField();
        ClaseDominio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsultaSubclass.setText("Consulta Subclass");
        ConsultaSubclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaSubclassActionPerformed(evt);
            }
        });

        jLabel1.setText("Consultas de Subclases");

        jLabel2.setText("Nombre subclase");

        CajaConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajaConsultaActionPerformed(evt);
            }
        });

        CajaResultados.setColumns(20);
        CajaResultados.setRows(5);
        jScrollPane1.setViewportView(CajaResultados);

        ConsultaSubpropiedad.setText("Consulta Subpropiedades");
        ConsultaSubpropiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaSubpropiedadActionPerformed(evt);
            }
        });

        jLabel3.setText("Consultas con subpropiedades");

        jLabel4.setText("Propiedad");

        jLabel5.setText("Lenguaje:");

        jLabel6.setText("Clase");

        Lenguaje_Propiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lenguaje_PropiedadActionPerformed(evt);
            }
        });

        Propiedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropiedadActionPerformed(evt);
            }
        });

        jLabel7.setText("Consulta de Dominio");

        jLabel8.setText("Lenguaje:");

        jLabel9.setText("Clase");

        LenguajeDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LenguajeDominioActionPerformed(evt);
            }
        });

        jButton1.setText("Consulta Dominio");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CajaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(ConsultaSubclass))
                                    .addComponent(Lenguaje_Propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(58, 58, 58)
                                        .addComponent(ConsultaSubpropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(ClaseDominio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                            .addComponent(LenguajeDominio, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CajaConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultaSubclass))
                .addGap(27, 27, 27)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Lenguaje_Propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Propiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConsultaSubpropiedad))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(LenguajeDominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(ClaseDominio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jButton1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CajaConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajaConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CajaConsultaActionPerformed

    private void ConsultaSubclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaSubclassActionPerformed
        String NombreSubclass = CajaConsulta.getText();
        String inputFileName = "Proyecto.rdf";
        Model model = ModelFactory.createDefaultModel();
        model.read(inputFileName);

        String resourcedURI = model.expandPrefix("pucp:" + NombreSubclass);
        Resource resource = model.getResource(resourcedURI);
        Selector selector = new SimpleSelector(resource, RDFS.subClassOf, (RDFNode) null);
        StmtIterator iter = model.listStatements(selector);
        while (iter.hasNext()) {
            CajaResultados.setText(iter.nextStatement().toString());
        }
        CajaConsulta.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaSubclassActionPerformed

    private void ConsultaSubpropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaSubpropiedadActionPerformed
        String LenguajePropiedad = Lenguaje_Propiedad.getText();
        String Propiedades = Propiedad.getText();
        String Clases = Clase.getText();

        String inputFileName = "Proyecto.rdf";
        Model model = ModelFactory.createDefaultModel();
        model.read(inputFileName);
        InfModel inf = ModelFactory.createRDFSModel(model);

        String resourceURI = model.expandPrefix("pucp:" + LenguajePropiedad);
        Resource kotlin = model.getResource(resourceURI);

        resourceURI = model.expandPrefix("pucp:" + Clases);
        Resource Ranking2 = model.getResource(resourceURI);
        String propertyURI = model.expandPrefix("pucp:" + Propiedades);
        Property puestoMejoresLenguajes = model.getProperty(propertyURI);

        Selector selector = new SimpleSelector(kotlin, puestoMejoresLenguajes, Ranking2);
        StmtIterator iter = inf.listStatements(selector);
        while (iter.hasNext()) {
            CajaResultados.setText(iter.nextStatement().toString());
        }


    }//GEN-LAST:event_ConsultaSubpropiedadActionPerformed

    private void Lenguaje_PropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lenguaje_PropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lenguaje_PropiedadActionPerformed

    private void PropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropiedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PropiedadActionPerformed

    private void LenguajeDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LenguajeDominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LenguajeDominioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String LenguajeDominios = LenguajeDominio.getText();
        String ClaseDominios = ClaseDominio.getText();
        
        String inputFileName = "Proyecto.rdf";
        Model model = ModelFactory.createDefaultModel();
        model.read(inputFileName);
        InfModel inf = ModelFactory.createRDFSModel(model);
        inf.setDerivationLogging(true);

        String resourceURI = model.expandPrefix("pucp:" + LenguajeDominios);
        Resource Kotlin = model.getResource(resourceURI);
        resourceURI = model.expandPrefix("pucp:"+ ClaseDominios);
        Resource lenguajeOrientadoObjetos = model.getResource(resourceURI);

        if (existenAfirmaciones(inf, Kotlin, RDF.type, lenguajeOrientadoObjetos)) {
            CajaResultados.setText("La afirmacion es cierta");
            mostrarDerivaciones(inf, Kotlin, RDF.type, lenguajeOrientadoObjetos);
        } else {
            CajaResultados.setText("La afirmacion no es cierta");
        }
    }

    public void mostrarDerivaciones(InfModel inf, Resource Sujeto, Property predicado, Resource objeto) {
        PrintWriter out = new PrintWriter(System.out);
        for (StmtIterator i = inf.listStatements(Sujeto, predicado, objeto); i.hasNext();) {
            Statement s = i.nextStatement();
            CajaResultados.setText("Statement is" + s);
            for (Iterator id = inf.getDerivation(s); id.hasNext();) {
                Derivation deriv = (Derivation) id.next();
                deriv.printTrace(out, true);
            }
        }
        out.flush();
    }

    public Boolean existenAfirmaciones(InfModel inf, Resource Sujeto,
            Property predicado, Resource objeto) {
        Boolean hayAfirmaciones;
        Selector selector = new SimpleSelector(Sujeto, predicado, objeto);
        StmtIterator iter = inf.listStatements(selector);
        hayAfirmaciones = iter.hasNext();
        return hayAfirmaciones;

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CajaConsulta;
    private javax.swing.JTextArea CajaResultados;
    private javax.swing.JTextField Clase;
    private javax.swing.JTextField ClaseDominio;
    private javax.swing.JButton ConsultaSubclass;
    private javax.swing.JButton ConsultaSubpropiedad;
    private javax.swing.JTextField LenguajeDominio;
    private javax.swing.JTextField Lenguaje_Propiedad;
    private javax.swing.JTextField Propiedad;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
